version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      # interval: weekly
      # day: sunday
    open-pull-requests-limit: 10
    target-branch: main
    versioning-strategy: increase
    commit-message:
      prefix: "chore"
      include: "scope"
