name: Publish
on:
  pull_request:
    types: [closed]
    branches:
      - main
      - production

env:
  GH_TOKEN: ${{ secrets.LERNA_RELEASE_TOKEN }}

jobs:
  publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: "Use NodeJS"
        uses: actions/setup-node@v2
        with:
          node-version: "17"

      - name: Set Git config
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor}}@users.noreply.github.com"

      - name: "Print changes"
        run: |
          npx lerna changed --all --json

      - name: "pre-release"
        if: ${{ github.base_ref == 'main' }}
        run: npx lerna version --conventional-commits --conventional-prerelease --preid beta --create-release github --yes

      - name: "release"
        if: ${{ github.base_ref == 'production' }}
        run: |
          npx lerna version --conventional-commits --conventional-graduate --create-release github --yes
          npx lerna publish from-git --create-release github --yes

      # - name: "update main with package.json stable version"
      #   if: ${{ github.base_ref == 'production' }}
      #   run: |
      #     git checkout main
      #     git status
      #     git add .
      #     git commit -m "chore(release): update to stable-release"
      #     git push
      # id: automerge
      # uses: "pascalgn/automerge-action@v0.15.3"
      # env:
      #   GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      ##2022-06-20T13:12:21.670Z INFO  Event name: pull_request
      ##2022-06-20T13:12:21.672Z INFO  Action ignored: pull_request closed
      ##2022-06-20T13:12:21.672Z INFO  Action result: { mergeResult: 'skipped' }

      # # since all our packages are private, this will never run, see Readme.md
      # - name: Publish release
      #   run: npx lerna publish from-git --create-release github --yes
