name: Deploy production

on:
  release:
    types:
      - released
  # push:
  #   branches:
  #     - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: simulate deploy
        env:
          RT: ${{ github.ref_type }}
          R: ${{ github.ref }}
        run: |
          echo "RT -> $RT"
          echo "R -> $R"
