name: Publish
on:
  pull_request:
    types: [closed]
    branches:
      - main
      - production

jobs:
  publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: "Use NodeJS 14"
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Set Git config
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor}}@users.noreply.github.com"

      - name: "pre-release"
        if: ${{ github.base_ref == 'main' }}
        run: npx lerna version --conventional-commits --conventional-prerelease --preid beta --yes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "release"
        if: ${{ github.base_ref == 'production' }}
        run: npx lerna version --conventional-commits --conventional-graduate --yes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish release
        run: npx lerna publish from-git --yes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
